name: Publish Theme

on: push

jobs:
  FTP-Deploy-Action:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: "sftp://preferatti.dev.forgedev.co/home/preferatti/wp-content/themes/dsq/"
        ftp-username: ${{ secrets.SFTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}