name: Publish Theme

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://preferatti.dev.forgedev.co/
        ftp-username: preferatti
        local-dir: /home/preferatti/wp-content/themes/dsq
        ftp-password: ${{ secrets.FTP_PASSWORD }}
